const $=s=>document.querySelector(s);let bank=[],rules={},tick=null,durationSeconds=90,deferredPrompt=null,audioCtx=null;const DB='examBankDB',STORE='kv',APP_VERSION='0.6.2';
function db(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function put(k,v){let d=await db();return new Promise((res,rej)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);t.oncomplete=res;t.onerror=()=>rej(t.error)})}async function get(k){let d=await db();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function clearDB(){let d=await db();return new Promise((res,rej)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).clear();t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function norm(r){return{大題:String(r['大題']??'').trim(),單元:String(r['單元']??'').trim(),題號:String(r['題號']??'').trim(),題目:String(r['題目']??'').trim()}}function majorSort(a,b){return a.localeCompare(b,undefined,{numeric:true})}function majors(){return[...new Set(bank.map(x=>x.大題))].sort(majorSort)}function valid(rows){return rows.map(norm).filter(x=>x.大題&&x.單元&&x.題目)}
function summary(){let ms=majors(),parts=ms.map(m=>`第${m}大題 ${bank.filter(x=>x.大題===m).length} 題`),txt=bank.length?`目前題庫：${parts.join('｜')}｜${new Set(bank.map(x=>x.單元)).size} 個單元`:'尚未匯入題庫';$('#ready').textContent=txt;$('#summary').textContent=txt;renderRules()}
function renderRules(){let box=$('#rulesBox'),ms=majors();box.innerHTML='';if(ms.length<2)return;let h=document.createElement('h3');h.textContent='抽題規則';box.appendChild(h);ms.forEach((m,i)=>{if(i===0)return;let row=document.createElement('div');row.className='rule-row';let lab=document.createElement('label');lab.textContent=`第${m}大題：`;let sel=document.createElement('select');sel.dataset.major=m;sel.innerHTML='<option value="">不限單元，隨機抽題</option>'+ms.slice(0,i).map(prev=>`<option value="${prev}">與第${prev}大題同單元</option>`).join('');sel.value=rules[m]||'';sel.onchange=async()=>{rules[m]=sel.value;await put('rules',rules)};row.append(lab,sel);box.appendChild(row)})}
function show(id){['home','exam','teacher'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}function fmt(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function setSeconds(s){durationSeconds=Math.max(10,Math.min(3599,Math.round(s)));$('#duration').textContent=fmt(durationSeconds)}function pick(a){return a[Math.floor(Math.random()*a.length)]}function newer(a,b){let A=a.split('.').map(Number),B=b.split('.').map(Number);for(let i=0;i<Math.max(A.length,B.length);i++){if((A[i]||0)!==(B[i]||0))return(A[i]||0)>(B[i]||0)}return false}
function initAudio(){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch(e){}}function beep(){try{initAudio();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.18,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.45);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.45)}catch(e){}}
async function checkUpdate(){let s=$('#updateStatus'),b=$('#updateBtn');b.classList.add('hidden');if(!navigator.onLine){s.textContent=`目前版本：v${APP_VERSION}｜目前離線，連上網路後可檢查新版`;return}try{let r=await fetch(`./version.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error();let latest=String((await r.json()).version||APP_VERSION);if(newer(latest,APP_VERSION)){s.textContent=`目前版本：v${APP_VERSION}｜最新版本：v${latest}｜有新版本可使用`;b.textContent=`更新至 v${latest}`;b.classList.remove('hidden')}else s.textContent=`目前版本：v${APP_VERSION}｜已是最新版本`}catch(e){s.textContent=`目前版本：v${APP_VERSION}｜暫時無法檢查新版`}}
async function doUpdate(){let b=$('#updateBtn'),s=$('#updateStatus');b.disabled=true;s.textContent='正在更新，題庫與設定會保留…';try{if('serviceWorker'in navigator){let reg=await navigator.serviceWorker.getRegistration();if(reg){await reg.update();let w=reg.waiting||reg.installing;if(w){await new Promise(resolve=>{if(w.state==='activated')return resolve();w.addEventListener('statechange',()=>{if(w.state==='activated')resolve()})})}}}s.textContent='更新完成，正在重新開啟…';setTimeout(()=>location.reload(),500)}catch(e){s.textContent='更新沒有完成，請確認網路後再試。';b.disabled=false}}
$('#minus').onclick=()=>setSeconds(durationSeconds-10);$('#plus').onclick=()=>setSeconds(durationSeconds+10);
$('#start').onclick=()=>{initAudio();let ms=majors();if(!ms.length)return alert('請先進入教師設定匯入題庫。');let chosen={},failed=[];for(let m of ms){let pool=bank.filter(x=>x.大題===m),ref=rules[m];if(ref&&chosen[ref])pool=pool.filter(x=>x.單元===chosen[ref].單元);if(!pool.length){failed.push(`第${m}大題找不到符合「與第${ref}大題同單元」的題目`);break}chosen[m]=pick(pool)}if(failed.length)return alert(failed[0]+'，請調整抽題規則或題庫。');let q=$('#questions');q.innerHTML='';ms.forEach(m=>{let x=chosen[m],box=document.createElement('div');box.className='qbox';box.innerHTML=`<h2>第${m}大題</h2><div class="qno"></div><div class="question"></div>`;box.querySelector('.qno').textContent=x.題號;box.querySelector('.question').textContent=x.題目;q.appendChild(box)});let s=durationSeconds;$('#countdown').textContent=fmt(s);show('exam');clearInterval(tick);tick=setInterval(()=>{s--;$('#countdown').textContent=fmt(Math.max(0,s));if(s<=0){clearInterval(tick);beep();setTimeout(()=>show('home'),800)}},1000)};
$('#teacherBtn').onclick=()=>{show('teacher');checkUpdate()};$('#back').onclick=()=>show('home');$('#updateBtn').onclick=doUpdate;
$('#importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let b=valid(await XLSXLite.read(f));if(!b.length)throw Error('找不到有效題目。請確認標題為：大題、單元、題號、題目');bank=b;let ms=majors();Object.keys(rules).forEach(k=>{if(!ms.includes(k)||!ms.includes(rules[k]))delete rules[k]});await put('bank',bank);await put('rules',rules);await put('bankFilename',f.name);summary();alert(`匯入完成，共 ${bank.length} 題、${ms.length} 大題。`)}catch(err){alert('匯入失敗：'+err.message)}finally{e.target.value=''}};
$('#exportBtn').onclick=async()=>bank.length?await XLSXLite.write(bank,(await get('bankFilename'))||'術科考試題庫.xlsx'):alert('目前沒有題庫可匯出。');$('#template').onclick=async()=>await XLSXLite.write([{大題:'1',單元:'範例單元A',題號:'1-01',題目:'請在此輸入第一大題題目'},{大題:'2',單元:'範例單元A',題號:'2-01',題目:'請在此輸入第二大題題目'},{大題:'3',單元:'範例單元B',題號:'3-01',題目:'第三大題可自行增加或刪除此列'}],'題庫匯入範本.xlsx');
$('#clearBtn').onclick=async()=>{if(!confirm('確定要清除這台裝置的題庫與所有抽題設定嗎？此動作無法復原，建議先匯出題庫備份。'))return;await clearDB();bank=[];rules={};setSeconds(90);summary();alert('本機題庫與設定已清除。')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden');$('#pwaStatus').textContent='✓ 可安裝 App；安裝後可離線使用'});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};window.addEventListener('appinstalled',()=>{$('#pwaStatus').textContent='✓ App 已安裝，可離線使用';$('#installBtn').classList.add('hidden')});
(async()=>{setSeconds(90);bank=await get('bank')||[];rules=await get('rules')||{};summary();let standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true,isIOS=/iphone|ipad|ipod/i.test(navigator.userAgent);if(standalone)$('#pwaStatus').textContent='✓ 已以 App 模式開啟，可離線使用';else if(isIOS)$('#iosHint').classList.remove('hidden');if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./service-worker.js');await navigator.serviceWorker.ready;if(!standalone&&!deferredPrompt)$('#pwaStatus').textContent='✓ 離線資料已準備完成；尚未安裝 App'}catch(e){$('#pwaStatus').textContent='⚠ 離線功能尚未就緒'}}})();